### PR TITLE
Remove seemingly unused/dead code

### PR DESCRIPTION
**Pull request by springmeyer**
Noticed that the `utils.js` is not used/tested. Queuing this up to consider removing it unless someone knows that this is in use downstream. If it is, then we'll need tests.

### CODE REVIEW

**Comment by springmeyer** [comment]
Looks like it was added in https://github.com/mapbox/node-mbtiles/commit/485342a9e85cfca86b8bc85c7096a885274ee076, but the code that used it has since been removed.

**Comment by mapsam** [comment]
@springmeyer 👍 from me

**Comment by springmeyer** [comment]
Thanks, @mapsam, merging.

**Comment by mapsam** [comment]
@springmeyer I imagine this will need to be a major bump, just in case anyone has begun relying on .utils? Will mark as vNext in the changelog

**Comment by mapsam** [comment]
Aha, we are pre 1.0 so this can just be a minor bump per the pre 1.x [semver docs](https://semver.org/)

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

**Comment by mapsam** [comment]
Added https://github.com/mapbox/node-mbtiles/commit/6febf74d623111c1c5b8d085ecd8bf89724e1e00

**Pull request merged**
