### PR TITLE
Add path.join so that pkg could auto detect assets

### PR DESCRIPTION
**Pull request by jingsam**
[pkg](https://github.com/zeit/pkg) could auto package assets if we use `path.join(__dirname, 'aaa.txt')`

### CODE REVIEW

**Comment by mapsam** [comment]
Thanks @jingsam - could you provide the error that pkg gives so I can try to recreate?

**Comment by jingsam** [comment]
This error is not display when you package it, but when you run your packaged app, it complaints:

```
Error: File '/**/foxgis-server-lite/node_modules/@mapbox/mbtiles/lib/schema.sql' was not included into executable at compilation stage. Please recompile adding it as asset or script.
    at error_ENOENT (pkg/prelude/bootstrap.js:422:17)
    at readFileFromSnapshot (pkg/prelude/bootstrap.js:646:29)
    at Object.fs.readFileSync (pkg/prelude/bootstrap.js:689:18)
    at Object.<anonymous> (/snapshot/foxgis-server-lite/node_modules/@mapbox/mbtiles/lib/mbtiles.js:28:21)
    at Module._compile (pkg/prelude/bootstrap.js:1243:22)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
```

**Comment by jingsam** [comment]
ping @mapsam

**Comment by mapsam** [comment]
@jingsam can you rebase against master to get tests passing again? Looks like the `utils` folder was removed in https://github.com/mapbox/node-mbtiles/pull/77

**Comment by jingsam** [comment]
ping @mapsam

**Comment by mapsam** [comment]
Thanks @jingsam - looks good!

**Pull request merged**
