### PR TITLE
add getTilestats method

### PR DESCRIPTION
**Pull request by mapsam**
Adds a `getTilestats` method that returns a tilestats object as defined by [mapbox-geostats](https://github.com/mapbox/mapbox-geostats) in preparation for mapbox-geostats to grab pre-existing `tilestats` rows in mbtiles files rather than generating them automatically.

cc @ericfischer @GretaCB @millzpaugh @springmeyer @yhahn

### CODE REVIEW

**Comment by mapsam** [comment]
@yhahn adding to `getInfo` makes a lot more sense - I was just focused on adding tilestats and got a little tunnel vision. Right now @ericfischer has been adding tilestats as a unique row to the mbtiles table - do you think we should add it to the `json` row instead?

**Comment by yhahn** [comment]
Yes, at least in the JS API any non scalar will get packed into the `json` row I believe.

**Comment by mapsam** [comment]
Well then! I think we don't need this PR 😄 `json` works great.

**Comment by mapsam** [comment]
Confirmed using the `json` field works just fine. Thank you for the review @yhahn!!

**Comment by yhahn** [comment]
:ok_hand:

**Pull request closed without merging**
