### PR TITLE
Use 'xyz' as scheme in metadata

### LINKED ISSUE #65: Inconsistent scheme in getInfo
Currently mbtiles [always reports](https://github.com/mapbox/node-mbtiles/blob/master/lib/mbtiles.js#L227) it's scheme as tms, even though it [swaps the z coordinate in getTile](https://github.com/mapbox/node-mbtiles/blob/master/lib/mbtiles.js#L149) in order to serve the tiles in xyz scheme.

### PR DESCRIPTION
**Pull request by hannesj**
As getTile swaps the z-coordinate from tms to xyz

Fixes #65

### CODE REVIEW

**Comment by jingsam** [comment]
ping @mapsam

**Comment by mapsam** [comment]
@flippmoke can you confirm this is 👍? Since you just want to confirm since you recently updated the mbtiles specification.

**Comment by jingsam** [comment]
ping @mapsam

**Comment by mapsam** [comment]
@jingsam thanks for the ping again- I've been hesitant to merge this only for the sake of being unsure about the downstream ramifications of switching this over. Should/does the `scheme` field represent the user expectations of the tileset (in which case `zxy` makes sense), or does it represent the internals of the MBTiles format (in which `tms` is the spec)? I'm unsure of how downstream tools may respond to the field, any experience here?

**Comment by hannesj** [comment]
Based on my understanding, the metadata should reflect what the tilelive api responds with. The internal storage within the mbtiles is just a implementation detail for the tilelive interface. I created this PR for us to be able to render tiles properly with https://github.com/mojodna/tessera

**Comment by jingsam** [comment]
@mapsam  I agree with @hannesj . `scheme` should be `tms` in metadata table to represent the internal of the MBTiles format. However, when users retrieve information form `getInfo` interface, the `scheme` should represent tile service scheme, which always be `xyz`.

**Comment by mapsam** [comment]
@jingsam @hannesj 👍 let's do it.

**Comment by jingsam** [comment]
@hannesj I think putInfo should also write `scheme: tms` into metadata table. Would you mind revise your PR and add some test?

**Pull request merged**
